### ISSUE TITLE
Forms should be ordered in some fashion

### ISSUE THREAD

**Issue by verdammelt** [exercism/common-lisp-representer#2]
For a representation of some file the forms should be sorted in some fashion. For example all defuns could be put together perhaps after all defvars. etc. etc.

**Comment by iHiD** [comment]
One thing to consider here is whether you would every want to give feedback because people are putting things in the wrong order. If not, this is a great thing to do. If you might want to give that feedback, then tread carefully here :)

**Comment by verdammelt** [comment]
Interesting point. I think I'll ask around to see what other languages are doing.

**Comment by verdammelt** [comment]
Decided *not* to sort forms for now. Closing this issue.
