### ISSUE TITLE
Representer needs to be deployed

### ISSUE THREAD

**Issue by verdammelt** [exercism/common-lisp-representer#3]
A placeholder issue to leave open until we have the representer deployed and working on new exercises.

TODO List:

- [x] exercism/terraform#14
- [x] #14

**Comment by iHiD** [comment]
So as an update to this, I realised that we don't have any representers installed. So I don't know how to do this. I know how to do test-runners :) When I work it out, you'll be top of the list ;)

**Comment by verdammelt** [comment]
First step: exercism/terraform#14

**Comment by iHiD** [comment]
Nope. That's all good I think! Feel free to add analyzer to the same terraform PR if you one of those too :)

**Comment by verdammelt** [comment]
Well i "have" an analyzer. it doesn't actually *analyze* but instead avoids analyzing by responding 'refer-to-mentor' :)

**Comment by verdammelt** [comment]
Representer is deployed (yay) and creating stack traces in production (boo)

**Comment by iHiD** [comment]
Progress!! :D
